openapi: "3.0.0"
info:
  version: 0.1.0
  title: BankAccount
  license:
    name: MIT
servers:
  - url: http://localhost:3000
paths:
  /account:
    get:
      summary: Get account information 
      tags:
        - account
      responses:
        '200':
          description: information about your account
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Account"
components:
  schemas:
    Account:
      type: object
      required:
        - clientId
        - accountNumber
      properties:
        clientId:
          type: number
        accountNumber:
          type: number
        owner:
            type: string